spring.application.name=backend
# Disable DB/Flyway autoconfig because this demo uses in-memory lists
spring.datasource.url=jdbc:h2:file:./data/jarbudget;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
